target("HeapTimer")
    set_kind("static")
    set_languages("cxx20")
    add_files("src/*.cpp")

target("test")
    set_kind("binary")
    add_files("test/*.cpp")
    add_deps("HeapTimer")
    set_languages("cxx20")
    add_syslinks("pthread")
    add_rpathdirs("/usr/local/gcc-11/lib")
    add_rpathdirs("/usr/local/gcc-11/lib64")